### ISSUE TITLE
Get Kweb working with Graal native-image

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#145]
Graal's [native-image](https://www.graalvm.org/docs/reference-manual/native-image/) has the ability to produce binaries from JVM jars *without* the overhead of having to include a JVM.

This could be interesting, for example, for building extremely lightweight Kweb-servers that start up very quickly, or if Kweb is running as part of a desktop app and we don't want to bundle a JRE with it.

The latest release of Graal - 20.1.0, [includes](https://medium.com/graalvm/graalvm-20-1-7ce7e89f066b) improved support for Kotlin coroutines.

After some experimentation I got it to build the native image with:

```bash
$ native-image --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime -jar kweb-core-0.7.12-all.jar
```
This jar is configured to run the ToDo demo when executed, the parameters ` --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime` 

It starts but runs into some issues:

```
 ~/I/k/kweb-core   $  build/libs  ./kweb-core-0.7.12-all                                                                                                                                                                                           Fri 22 May 2020 10:36:09 AM CDT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020-05-22 10:36:13.761:INFO::main: Logging initialized @4ms to org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at kotlin.random.Random.<clinit>(Random.kt:242)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init>(CoroutineScheduler.kt:638)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init>(CoroutineScheduler.kt:593)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.createNewWorker(CoroutineScheduler.kt:482)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker(CoroutineScheduler.kt:440)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker$default(CoroutineScheduler.kt:431)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.signalCpuWork$kotlinx_coroutines_core(CoroutineScheduler.kt:427)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch(CoroutineScheduler.kt:399)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch$default(CoroutineScheduler.kt:383)
	at kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatch(Dispatcher.kt:61)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:272)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kweb.Kweb.installRequiredKwebComponents(Kweb.kt:275)
	at kweb.Kweb.setupKweb(Kweb.kt:262)
	at kweb.Kweb.access$setupKweb(Kweb.kt:50)
	at kweb.Kweb$createServer$1$1.invoke(Kweb.kt:229)
	at kweb.Kweb$createServer$1$1.invoke(Kweb.kt:50)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:293)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:137)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:257)
	at io.ktor.server.jetty.JettyApplicationEngineBase.start(JettyApplicationEngineBase.kt:49)
	at io.ktor.server.jetty.JettyApplicationEngine.start(JettyApplicationEngine.kt:22)
	at io.ktor.server.jetty.JettyApplicationEngine.start(JettyApplicationEngine.kt:14)
	at io.ktor.server.engine.ApplicationEngine$DefaultImpls.start$default(ApplicationEngine.kt:56)
	at kweb.Kweb.<init>(Kweb.kt:83)
	at kweb.Kweb.<init>(Kweb.kt:72)
	at kweb.demos.todo.TodoApp.<init>(TodoApp.kt:35)
	at kweb.demos.todo.TodoAppKt.main(TodoApp.kt:18)
	at kweb.demos.todo.TodoAppKt.main(TodoApp.kt)
Caused by: java.lang.InstantiationException: Type `kotlin.internal.jdk8.JDK8PlatformImplementations` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:830)
	at kotlin.internal.PlatformImplementationsKt.<clinit>(PlatformImplementations.kt:41)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 39 more
2020-05-22 10:36:13.765:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT; built: unknown; git: unknown; jvm 11.0.7
2020-05-22 10:36:13.767:INFO:oejs.AbstractConnector:main: Started ServerConnector@66608fda{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:7659}
2020-05-22 10:36:13.767:INFO:oejs.Server:main: Started @10ms
2020-05-22 10:36:25.366:WARN:oeji.ManagedSelector:qtp1697539469-20: java.lang.ExceptionInInitializerError
2020-05-22 10:36:25.562:WARN:oeji.ManagedSelector:qtp1697539469-20: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.server.HttpOutput
2020-05-22 10:36:30.590:WARN:oeji.ManagedSelector:qtp1697539469-20: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.server.HttpOutput
```
It looks like Jetty is at least the initial culprit for it not working, I haven't yet tried to debug this further so it could be an easy fix.

**Comment by marad** [comment]
> Caused by: java.lang.InstantiationException: Type `kotlin.internal.jdk8.JDK8PlatformImplementations` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:830)

Looks to me like a reflective instantiation. Maybe [manual reflection configuration](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md#manual-configuration) is required here.
