### ISSUE TITLE
onClick Event on Safari / iPhone

### ISSUE THREAD

**Issue by frnknglrt** [kwebio/kweb-core#222]
Sorry, need to keep the report short today ;-)

**Describe the bug**
In the version 0.10.8, handling on.click Events on iOS / Safari fails with the following error: 
```
Fields [movementX, movementY] are required for type with serial name 'kweb.html.events.MouseEvent', but they were missing
```

This is the full stack trace:
```
Jul 17 16:29:00 berry3 java[945833]: kotlinx.serialization.MissingFieldException: Fields [movementX, movementY] are required for type with serial name 'kweb.html.events.MouseEvent', but they were missing
Jul 17 16:29:00 berry3 java[945833]:         at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.html.events.MouseEvent.<init>(events.kt:40)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.html.events.MouseEvent$$serializer.deserialize(events.kt:40)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.html.events.MouseEvent$$serializer.deserialize(events.kt:40)
Jul 17 16:29:00 berry3 java[945833]:         at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
Jul 17 16:29:00 berry3 java[945833]:         at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
Jul 17 16:29:00 berry3 java[945833]:         at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
Jul 17 16:29:00 berry3 java[945833]:         at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:104)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.html.events.OnReceiver$event$2.invoke(OnReceiver.kt:38)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.html.events.OnReceiver$event$2.invoke(OnReceiver.kt:30)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.html.events.OnReceiver$event$1.invoke(OnReceiver.kt:21)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.html.events.OnReceiver$event$1.invoke(OnReceiver.kt:21)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.Element$addEventListener$1.invoke(Element.kt:463)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.Element$addEventListener$1.invoke(Element.kt:461)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.Kweb.listenForWebsocketConnection(Kweb.kt:281)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.Kweb.access$listenForWebsocketConnection(Kweb.kt:44)
Jul 17 16:29:00 berry3 java[945833]:         at kweb.Kweb$listenForWebsocketConnection$1.invokeSuspend(Kweb.kt)
Jul 17 16:29:00 berry3 java[945833]:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
Jul 17 16:29:00 berry3 java[945833]:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
Jul 17 16:29:00 berry3 java[945833]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
Jul 17 16:29:00 berry3 java[945833]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
Jul 17 16:29:00 berry3 java[945833]:         at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
```
import kweb.*
import kweb.plugins.fomanticUI.fomantic
import kweb.plugins.fomanticUI.fomanticUIPlugin

fun main() {
  Kweb(port = 16097, plugins = listOf(fomanticUIPlugin)) {
    doc.body.new {
      button(fomantic.ui.button).text("Anmelden").apply {
                text.value="Anmelden"
                on.click {
                    println("Does not work in Safari on a iPhone")
                }
            }
    }
 }
}
```

**Expected behavior**
Click events shall work also on Safari iOS. Maybe we need to make the fields `movementX, movementY` nullable.

**Comment by sanity** [comment]
Should be fixed in `master`, would you mind testing and confirming?

```
	        implementation 'com.github.kwebio:kweb-core:-SNAPSHOT'
```

**Comment by frnknglrt** [comment]
Hello, 

Impressive! Will test it and report!

Viele Grüße,

Frank
