### ISSUE TITLE
class kweb.client.ClientConnection$WebSocket cannot be cast to class kweb.client.ClientConnection$Caching

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#488]
Occurs after Kweb server is restarted - probably not a significant production impact but annoying during debugging.

```
[qtp932285561-46] ERROR Application - Websocket handler failed
java.lang.ClassCastException: class kweb.client.ClientConnection$WebSocket cannot be cast to class kweb.client.ClientConnection$Caching (kweb.client.ClientConnection$WebSocket and kweb.client.ClientConnection$Caching are in unnamed module of loader 'app')
	at kweb.Kweb.listenForWebsocketConnection(Kweb.kt:271)
	at kweb.Kweb.access$listenForWebsocketConnection(Kweb.kt:44)
	at kweb.Kweb$listenForWebsocketConnection$1.invokeSuspend(Kweb.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sanity** [comment]
Fixed in 1.4.2
