### ISSUE TITLE
Support modifying multiple parts of a URL at once, such as path and query string

### ISSUE THREAD

**Issue by StefanHub** [kwebio/kweb-core#72]
How would [that ](http://docs.kweb.io/en/latest/routing.html#modifying-the-url) work with query parameters?

I also did not find a convenient way to retrieve query parametes. I ended up with:
```
fun WebBrowser.queryParameters() =
    parseQueryString(httpRequestInfo.requestedUrl.substringAfter("?").substringAfter("%3F"))
```
However, I was not able to modify the url such that it "hit" the route on the server.

**Comment by sanity** [comment]
Something like this should now work with `-SNAPSHOT`, I'll release 0.5.2 shortly with this functionality:

```kotlin
    Kweb(port = 23423) {
        val queryKvar = url(simpleUrlParser).query
        doc.body.new {
            render(queryKvar) {
                h3().text(queryKvar.map { "Query: $it" })
                button().on.click {
                    queryKvar.value = "newquerystring"
                }
            }
        }
    }
```

**Comment by sanity** [comment]
Oh, note that it's preferable to access the URL via `url(simpleUrlParser)`, as this will correctly handle URL modifications.

**Comment by StefanHub** [comment]
With 0.5.2 just adding

    val queryKvar = url(simpleUrlParser).query

results in

    [ktor-jetty-16097-1] ERROR io.kweb.WebBrowser - Exception thrown building page
    java.lang.IllegalStateException: from.query() must not be null
    	at io.kweb.state.KVarExtensionsKt$query$1.invoke(KVarExtensions.kt:55)
    	at io.kweb.state.KVarExtensionsKt$query$1.invoke(KVarExtensions.kt:53)
    	at io.kweb.state.KVar.map(KVar.kt:27)
    	at io.kweb.state.KVarExtensionsKt.getQuery(KVarExtensions.kt:53)
    	at MainKt$main$1$1.invoke(Main.kt:17)
    	at MainKt$main$1$1.invoke(Main.kt)
    	at io.kweb.dom.element.ElementKt.new(Element.kt:334)
    	at io.kweb.dom.element.ElementKt.new$default(Element.kt:331)
    	at MainKt$main$1.invoke(Main.kt:15)
    	at MainKt$main$1.invoke(Main.kt)
    	at io.kweb.Kweb$listenForHTTPConnection$1$2.invoke(Kweb.kt:205)
    	at io.kweb.Kweb$listenForHTTPConnection$1$2.invoke(Kweb.kt:50)
    	at io.kweb.MiscKt.warnIfBlocking(misc.kt:33)
    	at io.kweb.Kweb$listenForHTTPConnection$1.invokeSuspend(Kweb.kt:194)
    	at io.kweb.Kweb$listenForHTTPConnection$1.invoke(Kweb.kt)
    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
    	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
    	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
    	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
    	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
    	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
    	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
    	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
    	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
    	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:118)
    	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
    	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
    	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
    	at io.ktor.server.jetty.JettyKtorHandler$handle$2.invokeSuspend(JettyKtorHandler.kt:102)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)

**Comment by sanity** [comment]
Doh, didn't account for query() returning null, please try 0.5.3 - just released.

**Comment by StefanHub** [comment]
Great! No exceptions!

Now I am trying to redirect the url with

    path.value = "/amount/?firstName=${firstName.value}&lastName=${lastName.value}"

so that another path can fetch the data from the query string. But this generates the following url in the browser

    http://localhost:16097/amount/%3FfirstName=a&lastName=b

which than results in a "not found" although the route/path "/amount/" exists.

**Comment by sanity** [comment]
Hmm, yes - I would expect it to escape the `?` so that the query can be part of the path.

I probably need to think through this use-case more, but for now you could try something like this for the redirect:

```kotlin
val url = url(simpleUrlParser)
// ...
url.value = url.value.withPath("/amount/").withQuery("firstName=${firstName.value}&lastName=${lastName.value}")
```

**Comment by sanity** [comment]
@StefanHub Any luck?

**Comment by StefanHub** [comment]
Unfortunately, no.

After the

                                    url.value = url.value.withPath("/amount/")
                                       .withQuery("firstName=${firstName.value}&lastName=${lastName.value}")

the 

    println(url.value)

returns what I would expect:

    http://localhost:16097/amount/?firstName=a&lastName=b

but the browser does not show the query parameters and the routing results in "page not found"

**Comment by sanity** [comment]
Crap.

If you could provide a minimal stand-alone test-case that reproduces the problem, I'm sure I can get this fixed quickly.  It's just that without knowing the context I might end up spinning my wheels.

**Comment by StefanHub** [comment]
Yes, of course - although it is not the prettiest code :-)

    import io.kweb.Kweb
    import io.kweb.dom.element.creation.tags.*
    import io.kweb.dom.element.events.on
    import io.kweb.dom.element.new
    import io.kweb.routing.route
    import io.kweb.state.KVar
    import io.kweb.state.query
    import io.kweb.state.simpleUrlParser
    
    fun main() {
        Kweb(port = 16097) {
            doc.body.new {
                val url = url(simpleUrlParser)
    //            val path = url(simpleUrlParser).path
                val queryKvar = url(simpleUrlParser).query  // TODO: https://github.com/kwebio/kweb-core/issues/72
                route {
                    path("/input/") {
                        val firstName = KVar<String>("")
                        val lastName = KVar<String>("")
                        label().text("Vorname: ")
                        input(InputType.text, placeholder = "Vorname").setValue(firstName)
                        div()
                        label().text("Nachname: ")
                        input(InputType.text, placeholder = "Nachname").setValue(lastName)
                        div()
                        button()
                            .apply {
                                text("Weiter")
                                on.click {
                                    println("Entered: $firstName $lastName")
    //                                println(queryKvar)
    //                                path.value = "/amount/${firstName.value}/${lastName.value}"
                                    //path.value = "/amount/?firstName=${firstName.value}&lastName=${lastName.value}"
    
                                    url.value = url.value.withPath("/amount/")
                                        .withQuery("firstName=${firstName.value}&lastName=${lastName.value}")
                                    println("Redirecting to ${url.value}")
                                }
                            }
                    }
    //                path("/amount/{firstName}/{lastName}") { params ->
                    path("/amount/") { params ->
                        // val queries = queryParameters()
                        println("QuerVar: $queryKvar")
                        val firstName = params["firstName"]?.value ?: "?"
                        val lastName = params["lastName"]?.value ?: "?"
    
                        label().text("Kunde: $firstName $lastName")
                        div()
                        val beitrag = KVar<String>("0.0")
                        input(InputType.text, placeholder = "Beitrag").setValue(beitrag)
    
                        div()
                        button()
                            .apply {
                                text("Weiter")
                                on.click {
                                    println("$firstName $lastName")
    //                                path.value = "/amount/${firstName}/${lastName}/${beitrag.value}"
                                }
                            }
                    }
                    path("/result/{firstName}/{lastName}/{beitrag}") { params ->
                        // val queries = queryParameters()
                        val firstName = params["firstName"]
                        val lastName = params["lastName"]
                        val beitrag = params["beitrag"]?.value?.toDouble() ?: Double.NaN
    
                        label().text("Ergebnis: ${beitrag * 2}")
                    }
                    notFound {
                        h1().text("Page not found!")
                    }
                }
            }
        }
    }

**Comment by sanity** [comment]
Thank you, and just one additional clarification if you wouldn't mind.

What is the expected behavior of this code, and what is the actual behaior?

**Comment by StefanHub** [comment]
Yes, sorry.

The idea is to have 3 different pages/routes which all can be called (http request) independently of each other. But the first page (/input) collects some data that it passes (redirects) to the second page (/amount) with the collected data as query parameters. Similar with second to third page.

**Comment by sanity** [comment]
Thank you.  I'll try to dig into this today or tomorrow - are you blocking on it?

**Comment by StefanHub** [comment]
No, it´s ok.

Thanks!

**Comment by PotatoCurry** [comment]
Any updates on this issue? I experience a similar problem with the below code.
```kotlin
path.value = "/game/$code?user=${user.uid}"
```
This code ought to create a path resembling something like this: `/game/4RF2?user=431429`.
Instead, it produces this: `/game/4RF2%3Fuser=431429`.

**Comment by sanity** [comment]
I'm afraid I haven't had a chance to dig further into this yet, apologies.

The reason that isn't working is because the part after the `?` in a URL is part of the "query" rather than the path:

```
URI = scheme:[//authority]path[?query][#fragment]
```

Does this work for you?

```
val url = url(simpleUrlParser)
// ...
url.value = url.value.withPath("/game/$code").withQuery("user=${user.uid}")
```

**Comment by sanity** [comment]
`url.value` can now include a path, query, and fragment, eg this now works:

```kotlin
url.value = "/game/code?user=1345"
```
