### ISSUE TITLE
browser.evaluate fails when response is an array

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#93]
Hey there!

Issue summary: When `browser.evaluate(js)` is called and produces a JSON Array response, Gson throws an exception.

Use case: I am using a [multiple selection dropdown](https://stackoverflow.com/a/37598393) in fomantic. When I call 
`"${'$'}('.ui.dropdown').dropdown('get value');"` 
the response is a json array, which blows up gson

Stacktrace:
```
Jan 23, 2020 5:34:03 PM io.kweb.Kweb$listenForWebsocketConnection$1 invokeSuspend
SEVERE: Exception while receiving websocket message
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 60 path $.callback.data
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at io.kweb.Kweb$listenForWebsocketConnection$1.invokeSuspend(Kweb.kt:423)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 60 path $.callback.data
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	... 11 more
```

Suggested fix: Unsure, but I am temporarily using
` "${'$'}('.ui.dropdown').dropdown('get value').toString();" `
as my js script, to get the response as a string value and it works

Example: https://github.com/alkoclick/kweb-core/commit/8f518054270aef87aeec99c8f4ab44ff81e829e3

**Comment by sanity** [comment]
I believe this is now fixed in `master`, would you mind verifying?

**Comment by alkoclick** [comment]
Can confirmed that the issue is fixed in my example and also my working code. Feel free to close and let me know if you make a release of this, I'd love to jump off of "SNAPSHOT" :D 

Great work btw, and thanks for being so responsive!

**Comment by alkoclick** [comment]
Could you possibly look into using generics (I dunno if a reified type may be required) to actually get a `CompletableFuture<T>` instead of Any? The api currently requires a lot of casting

**Comment by sanity** [comment]
Yes, I think that should be doable but I would need to think through the Gson part of it a bit more.

In the meantime I'll do a release of the existing fix.

**Comment by sanity** [comment]
0.5.13 released.

**Comment by alkoclick** [comment]
Closing this as the bug is resolved. Cheers!
